#!/usr/bin/env python3

def calculator():
    while(True):
        num1= input("Enter your first number: ")
        try:
            num1 = int(num1)
            break
        except:
            print("You must enter a number!")

    while(True):
        num2=input("Enter your second number: ")
        try:
            num2= int(num2)
            break
        except:
            print("You must enter a number!")
    print(f"{num1} + {num2} = {num1 + num2}")

calculator() 
